name: Castle_defence
version: '${version}'

main: me.dkprog.castle_defence.Castle_defence
api-version: '1.21.8'
load: POSTWORLD
commands:
  visualizeneighbors:
    description: Показывает количество соседей у каждого структурного блока в слоте
    usage: /<command>
  visualizehp:
    description: Показывает оставшееся ХП (порог - накопленный урон) каждого структурного блока в слоте, голограммой со смещением +15 по X
    usage: /<command>
  setplayerclass:
    description: Присваивает класс игроку
    usage: /<command> <player> <class>
  visualizebuildboxes:
    description: Показывает границы всех зон строительства
    usage: /<command>